export const GET_IMAGE = 'GET_IMAGE';
export const ADD_IMAGE = 'ADD_IMAGE';
export const IMAGE_IS_LOADING = 'IMAGE_IS_LOADING';
export const HANDLE_IMAGE_ERROR = 'HANDLE_IMAGE_ERROR';
export const IMAGE_ROLLBACK = 'IMAGE_ROLLBACK';

export const GET_NAME = 'GET_NAME';
export const DELETE_IMAGE = 'DELETE_NAME';
export const ADD_NAME = 'SET_NAME';
export const NAME_IS_LOADING = 'NAME_IS_LOADING';
export const HANDLE_NAME_ERROR = 'HANDLE_IMAGE_ERROR';

export const GET_CREDENTIALS = 'GET_CREDENTIALS';
export const ADD_CREDENTIALS = 'SET_CREDENTIALS';
export const CREDENTIALS_IS_LOADING = 'CREDENTIALS_IS_LOADING';
export const HANDLE_CREDENTIALS_ERROR = 'HANDLE_CREDENTIALS_ERROR';
